version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./public:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: .
    volumes:
      - ./public:/var/www/html
      - ./logs:/greensight/logs